[versions]
precompose = "1.6.0"

[libraries]
precompose-viewmodel = {module = "moe.tlaster:precompose-viewmodel", version.ref = "precompose"}
precompose = {module = "moe.tlaster:precompose", version.ref = "precompose"}

[plugins]

